# Generated by Django 5.0.3 on 2024-03-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
