# Generated by Django 5.0.3 on 2024-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
